<a href="https://colab.research.google.com/github/jyotirangu/DataScience/blob/main/11_NumPy/0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [3]:
import numpy as np

a = np.array([1,2,3])
print(a)

# Output in the form of vector

[1 2 3]


In [4]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

# output in the form of matrix

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(c)

# output in the form of tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# We can change the data type of the item stored in np.array as by default it is integer, we can set as follow
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
# np.arrange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# With reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [9]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.randome
np.random.random((3,4))

array([[0.63073323, 0.11167653, 0.37855047, 0.6258711 ],
       [0.41938169, 0.87033017, 0.63837334, 0.07167589],
       [0.61206547, 0.91984423, 0.80961604, 0.25070593]])

In [12]:
# np.linspace
np.linspace(-10,10,10)
# np.linspace(-10,10,10,dtype=int)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
# np.identity
np.identity(3)

# It is used to create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [20]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
# ndim
a3.ndim

3

In [25]:
# shape
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [26]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
# size
a3.size

8

In [29]:
# itemsize
a3.itemsize

8

In [31]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


### Changing Datatype

In [32]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [35]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [55]:
a2 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[       0,  1000000,  2000000,  3000000],
       [ 4000000,  5000000,  6000000,  7000000],
       [ 8000000,  9000000, 10000000, 11000000]])

In [38]:
# max/min/sum/prod
np.max(a1)

np.int64(1100)

In [39]:
np.min(a1)

np.int64(0)

In [40]:
np.sum(a1)

np.int64(6600)

In [41]:
np.prod(a1)

np.int64(0)

In [45]:
# 0 -> col and 1 -> row
print(np.max(a1,axis=0))
# It is used to find max value in each column
print(np.max(a1,axis=1))
# It is used to find max value in each row

[ 800  900 1000 1100]
[ 300  700 1100]


In [46]:
# mean/median/std/var
np.mean(a1)

np.float64(550.0)

In [47]:
np.mean(a1,axis=1)

array([150., 550., 950.])

In [49]:
np.median(a1)

np.float64(550.0)

In [50]:
np.std(a1,axis=1)

array([111.80339887, 111.80339887, 111.80339887])

In [51]:
np.var(a1)

np.float64(119166.66666666667)

In [52]:
# trigonomoentry
np.sin(a1)

array([[ 0.        , -0.50636564, -0.8732973 , -0.99975584],
       [-0.85091936, -0.46777181,  0.04418245,  0.54397052],
       [ 0.89396965,  0.99780327,  0.82687954,  0.42826439]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

In [53]:
# log and exponents
np.log(a1)

/tmp/ipython-input-53-1113725948.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 4.60517019, 5.29831737, 5.70378247],
       [5.99146455, 6.2146081 , 6.39692966, 6.55108034],
       [6.68461173, 6.80239476, 6.90775528, 7.00306546]])

In [56]:
np.exp(a1)

/tmp/ipython-input-56-1498217415.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(a1)


array([[ 1., inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [61]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[82., 39., 15.],
       [ 3., 36., 72.]])

In [62]:
np.ceil(np.random.random((2,3))*100)

array([[86., 29., 72.],
       [16., 15., 80.]])

In [63]:
np.floor(np.random.random((2,3))*100)

array([[20., 14., 15.],
       [64., 17., 43.]])

### Indexing and Slicing

In [65]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a1[-1]

np.int64(9)

In [68]:
a1[0]

np.int64(0)

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a2[1,2]

np.int64(6)

In [71]:
a2[2,3]

np.int64(11)

In [72]:
a2[1,0]

np.int64(4)

In [73]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [74]:
a3[1,0,1]

np.int64(5)

In [75]:
a3[0,1,0]

np.int64(2)

In [76]:
a3[0,0,0]

np.int64(0)

In [77]:
a3[1,1,1]

np.int64(7)

In [78]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a1[2:5:2]

array([2, 4])

In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a2[0,:]

array([0, 1, 2, 3])

In [90]:
a2[:,2]

array([ 2,  6, 10])

In [89]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [91]:
a2[:2,2:]

array([[2, 3],
       [6, 7]])

In [95]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [96]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [107]:
a2[1,::3]

array([4, 7])

In [109]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [110]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [113]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
a3[1]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [115]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
a3[0,1,:]

array([3, 4, 5])

In [130]:
a3[1,:,1]

array([10, 13, 16])

In [133]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [136]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

####Iterating

In [141]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [143]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2

for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [144]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [145]:
a3

for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [146]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


####Reshaping

In [ ]:
# reshape

In [149]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [152]:
# ravel converst multidimensional array to single dimensional array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [153]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

###Stacking

In [159]:
# horizontal splitting
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [158]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [160]:
# vertical splitting
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###Splitting

In [161]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [165]:
#vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [167]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]