<a href="https://colab.research.google.com/github/jyotirangu/DataScience/blob/main/11_NumPy/1_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [2]:
a = np.nan*np.empty(10)
a[4] = 1
print(a)

[nan nan nan nan  1. nan nan nan nan nan]


### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
a = int(input("Enter the first number : "))
b = int(input('Enter the second number : '))
c = np.random.random((a,b))
print(c)
print(c.mean())

Enter the first number : 4
Enter the second number : 4
[[0.94009    0.21155326 0.11316788 0.90814449]
 [0.24153479 0.17001308 0.08174917 0.36889183]
 [0.7524922  0.85712356 0.27132244 0.16680252]
 [0.65339037 0.50378314 0.67222023 0.21478274]]
0.4454413552930195


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [4]:
def borderArray(a,b):
  x = np.ones((a,b))
  x[1:-1,1:-1] = 0
  return x

a = borderArray(4,4)
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [5]:
#Code here
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [6]:
a = np.random.randint(1,100,(10,2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([ 86,  98,  59,  85,  95, 110,  96,  82,  77, 100])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [7]:
a = np.zeros((6,7,8))
print(a)
np.unravel_index(100, (6,7,8))

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [8]:
a = input().strip().split()
a
np.array(a[::-1], dtype=np.float32)

1 5 6


array([6., 5., 1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
a = np.array([])
a = np.array([1,2])
a = np.zeros((2,3))
a.size

6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [9]:
def softmax(arr):
  if type(arr) is not np.ndarray:
    raise TypeError('Requires Numpy Array')
  elif arr.ndim >1:
    raise TypeError('Requires 1D Array')
  s = np.sum(np.exp(arr))
  return np.exp(arr)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [10]:
def vertical_stack(*args):
  for i in args:
    if type(i)!=np.ndarray:
      raise TypeError("Requires Numpy Array")
  return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a ",a)
b = np.repeat(1,10).reshape(2,-1)
print("b ",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
print("c ",c)
print(vertical_stack(a,b,c))

a  [[0 1 2 3 4]
 [5 6 7 8 9]]
b  [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c  [[0.06310565 0.00412702 0.9239863  0.73549167 0.9370253 ]
 [0.91714515 0.32226244 0.7665417  0.39690023 0.22693656]]
[[0.00000000e+00 1.00000000e+00 2.00000000e+00 3.00000000e+00
  4.00000000e+00]
 [5.00000000e+00 6.00000000e+00 7.00000000e+00 8.00000000e+00
  9.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]
 [6.31056489e-02 4.12702176e-03 9.23986302e-01 7.35491666e-01
  9.37025299e-01]
 [9.17145148e-01 3.22262438e-01 7.66541700e-01 3.96900229e-01
  2.26936556e-01]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [14]:
def date_array(start: str, end: str):
  if type(start) != str or type(end) != str:
    raise TypeError("Requires String")

  total_days_of_month = {'01':31, '02':28, '03':31, '04':30, '05':31, '06':30, '07':31, '08':31, '09':30, '10':31, '11':30, '12':31}

  end = end.split("-")
  end_last = int(end[-1]) + 1

  if total_days_of_month[end[-2]] < end_last:
    days_diff = end_last - total_days_of_month[end[-2]]
    end[-1] = f'0{days_diff}' if days_diff < 10 else f'{days_diff}'
    next_month = int(end[-2]) + 1
    end[-2] = f'0{next_month}' if next_month < 10 else f'{next_month}'
  else:
    end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
  end = "-".join(end)
  return np.arange(start, end, dtype='datetime64[D]')

date_array(start = '2022-11-01', end = '2022-11-30')


array(['2022-11-01', '2022-11-02', '2022-11-03', '2022-11-04',
       '2022-11-05', '2022-11-06', '2022-11-07', '2022-11-08',
       '2022-11-09', '2022-11-10', '2022-11-11', '2022-11-12',
       '2022-11-13', '2022-11-14', '2022-11-15', '2022-11-16',
       '2022-11-17', '2022-11-18', '2022-11-19', '2022-11-20',
       '2022-11-21', '2022-11-22', '2022-11-23', '2022-11-24',
       '2022-11-25', '2022-11-26', '2022-11-27', '2022-11-28',
       '2022-11-29', '2022-11-30'], dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [17]:
x = np.random.random((5,4))
x - x.mean(axis = 1, keepdims=True)

array([[ 0.27891325,  0.04230479, -0.04364266, -0.27757539],
       [ 0.33914056, -0.04235478, -0.1438029 , -0.15298288],
       [-0.12944212,  0.39361762,  0.073628  , -0.3378035 ],
       [ 0.23382966,  0.30873152, -0.26130339, -0.28125779],
       [ 0.19204107, -0.02257541,  0.32393097, -0.49339663]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [21]:
x = np.arange(9).reshape(3,3)
print(x)
x[:,[0,2,1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [23]:
a = np.arange(10)
print(a)
a[a % 2 == 1] = -1
a


[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [26]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [27]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8654, 2102, 8790, 8044, 6186],
       [  74, 4118, 5894, 2718, 1071],
       [5420, 6052, 2324, 5663, 9517],
       [9363, 4292, 5976,  931, 2809],
       [9995, 4566, 5475,  286, 8501],
       [5014, 3194, 1024, 8263, 7638],
       [2819, 3360, 5741, 2192, 1403],
       [6744,  611, 9202,  276, 9629]])

In [28]:
arr1[:,::2]

array([[8654, 8790, 6186],
       [  74, 5894, 1071],
       [5420, 2324, 9517],
       [9363, 5976, 2809],
       [9995, 5475, 8501],
       [5014, 1024, 7638],
       [2819, 5741, 1403],
       [6744, 9202, 9629]])

In [29]:
arr1.max()

np.int64(9995)

In [30]:
arr1.min()

np.int64(74)

In [31]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.86483217, 0.20441488, 0.87854047, 0.80334644, 0.61606693],
       [0.        , 0.4076202 , 0.58663441, 0.26650539, 0.1004939 ],
       [0.53885697, 0.60256023, 0.22679165, 0.56335047, 0.95181937],
       [0.93629674, 0.42515875, 0.59489971, 0.08638242, 0.27567786],
       [1.        , 0.45277694, 0.54440077, 0.02136881, 0.84941034],
       [0.49793368, 0.31448443, 0.09575648, 0.82542082, 0.76242314],
       [0.27668582, 0.33121661, 0.57121258, 0.21348654, 0.13395827],
       [0.67231126, 0.05412761, 0.92006854, 0.02036085, 0.96310856]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [33]:
def nthmax(arr, n):
  if n > len(arr):
    raise IndexError("n is greater than length of array")
  arr.sort()
  return arr[n]
nthmax(np.array([12, 34, 40, 7, 1, 0]), 2)

None


np.int64(7)

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [40]:
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])
# np.repeat(a,3)
# np.tile(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])