<a href="https://colab.research.google.com/github/jyotirangu/DataScience/blob/main/11_NumPy/3_NumPy_Tricks_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [3]:
np.sort(a)

# this will sort the array in ascending order

array([12, 22, 23, 26, 26, 28, 46, 52, 53, 56, 60, 61, 63, 65, 70])

In [6]:
np.sort(a)[::-1]
# This will sort the array in descending order

array([70, 65, 63, 61, 60, 56, 53, 52, 46, 28, 26, 26, 23, 22, 12])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[49, 54, 54, 20],
       [30,  8, 78, 32],
       [ 3, 64, 67, 96],
       [95, 29, 89, 51],
       [91, 58, 73,  5],
       [81, 35, 36, 77]])

In [4]:
np.sort(b)
# sorting will be done row-wise

array([[20, 49, 54, 54],
       [ 8, 30, 32, 78],
       [ 3, 64, 67, 96],
       [29, 51, 89, 95],
       [ 5, 58, 73, 91],
       [35, 36, 77, 81]])

In [5]:
np.sort(b, axis=0)
# Column wise sorting

array([[ 3,  8, 36,  5],
       [30, 29, 54, 20],
       [49, 35, 67, 32],
       [81, 54, 73, 51],
       [91, 58, 78, 77],
       [95, 64, 89, 96]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:

np.append(a,200)

array([ 26,  22,  65,  46,  61,  60,  53,  52,  28,  70,  26,  23,  12,
        56,  63, 200])

In [8]:
b

array([[49, 54, 54, 20],
       [30,  8, 78, 32],
       [ 3, 64, 67, 96],
       [95, 29, 89, 51],
       [91, 58, 73,  5],
       [81, 35, 36, 77]])

In [9]:
# add one more column to be with value 1
np.append(b,np.ones((b.shape[0],1)))

array([49., 54., 54., 20., 30.,  8., 78., 32.,  3., 64., 67., 96., 95.,
       29., 89., 51., 91., 58., 73.,  5., 81., 35., 36., 77.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [11]:
# Above code first convert 2D array to 1D array then add 1's, to achieve this in column as follow
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[49., 54., 54., 20.,  1.],
       [30.,  8., 78., 32.,  1.],
       [ 3., 64., 67., 96.,  1.],
       [95., 29., 89., 51.,  1.],
       [91., 58., 73.,  5.,  1.],
       [81., 35., 36., 77.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
e = np.array([1,1,1,1,2,3,4,2,3,5,3,5,5,4,6,7])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [18]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [20]:
a.shape

(15,)

In [19]:
np.expand_dims(a,axis=0)

array([[26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63]])

In [21]:
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [24]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [25]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  4,  5,  6,  7,  9, 13, 14]),)

In [27]:
# replace all values > 50 with 0
# np.where(a>50,True,False)
np.where(a>50,0,a)

array([26, 22,  0, 46,  0,  0,  0,  0, 28,  0, 26, 23, 12,  0,  0])

In [28]:
# Replace all even numbers with 0
np.where(a%2==0,0,a)

array([ 0,  0, 65,  0, 61,  0, 53,  0,  0,  0,  0, 23,  0,  0, 63])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [29]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [30]:
np.argmax(a)

np.int64(9)

In [31]:
b

array([[49, 54, 54, 20],
       [30,  8, 78, 32],
       [ 3, 64, 67, 96],
       [95, 29, 89, 51],
       [91, 58, 73,  5],
       [81, 35, 36, 77]])

In [32]:
np.argmax(b,axis=0)
# 0 --> row

array([3, 2, 3, 2])

In [33]:
np.argmax(b,axis=1)

array([1, 2, 3, 0, 0, 0])

In [34]:
# np.argmin
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [35]:
np.argmin(a)

np.int64(12)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [36]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [37]:
np.cumsum(a)

array([ 26,  48, 113, 159, 220, 280, 333, 385, 413, 483, 509, 532, 544,
       600, 663])

In [38]:
b

array([[49, 54, 54, 20],
       [30,  8, 78, 32],
       [ 3, 64, 67, 96],
       [95, 29, 89, 51],
       [91, 58, 73,  5],
       [81, 35, 36, 77]])

In [39]:
np.cumsum(b)

array([  49,  103,  157,  177,  207,  215,  293,  325,  328,  392,  459,
        555,  650,  679,  768,  819,  910,  968, 1041, 1046, 1127, 1162,
       1198, 1275])

In [40]:
np.cumsum(b,axis=0)

array([[ 49,  54,  54,  20],
       [ 79,  62, 132,  52],
       [ 82, 126, 199, 148],
       [177, 155, 288, 199],
       [268, 213, 361, 204],
       [349, 248, 397, 281]])

In [41]:
np.cumsum(b,axis=1)

array([[ 49, 103, 157, 177],
       [ 30,  38, 116, 148],
       [  3,  67, 134, 230],
       [ 95, 124, 213, 264],
       [ 91, 149, 222, 227],
       [ 81, 116, 152, 229]])

In [42]:
# cumprod
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [44]:
np.cumprod(a)

array([                  26,                  572,                37180,
                    1710280,            104327080,           6259624800,
               331760114400,       17251525948800,      483042726566400,
          33812990859648000,   879137762350848000,  1773424460359952384,
        2834349450609876992, -7297127429232852992,  1449573801069051904])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [45]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [46]:
np.percentile(a,100)
# 100 means the maximum number in a

np.float64(70.0)

In [48]:
np.percentile(a,50)

np.float64(52.0)

In [49]:
np.percentile(a,10)

np.float64(22.4)

In [50]:
np.median(a)

np.float64(52.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [51]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [53]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 5, 0, 1, 3, 4, 1, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [54]:
np.histogram(a,bins=[50,100])

(array([8]), array([ 50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [56]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [57]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [60]:
# list of items to be searched
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False, False])

In [59]:
a[np.isin(a,items)]

array([60, 70])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [61]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [62]:
np.flip(a)

array([63, 56, 12, 23, 26, 70, 28, 52, 53, 60, 61, 46, 65, 22, 26])

In [63]:
b

array([[49, 54, 54, 20],
       [30,  8, 78, 32],
       [ 3, 64, 67, 96],
       [95, 29, 89, 51],
       [91, 58, 73,  5],
       [81, 35, 36, 77]])

In [64]:
np.flip(b)

array([[77, 36, 35, 81],
       [ 5, 73, 58, 91],
       [51, 89, 29, 95],
       [96, 67, 64,  3],
       [32, 78,  8, 30],
       [20, 54, 54, 49]])

In [65]:
np.flip(b,axis=0)

array([[81, 35, 36, 77],
       [91, 58, 73,  5],
       [95, 29, 89, 51],
       [ 3, 64, 67, 96],
       [30,  8, 78, 32],
       [49, 54, 54, 20]])

In [66]:
np.flip(b,axis=1)

array([[20, 54, 54, 49],
       [32, 78,  8, 30],
       [96, 67, 64,  3],
       [51, 89, 29, 95],
       [ 5, 73, 58, 91],
       [77, 36, 35, 81]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [67]:
a

array([26, 22, 65, 46, 61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

In [68]:
np.put(a,[0,1],[110,530])
# changes happened in the memory

In [69]:
a

array([110, 530,  65,  46,  61,  60,  53,  52,  28,  70,  26,  23,  12,
        56,  63])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [70]:
a

array([110, 530,  65,  46,  61,  60,  53,  52,  28,  70,  26,  23,  12,
        56,  63])

In [71]:
np.delete(a,0)

array([530,  65,  46,  61,  60,  53,  52,  28,  70,  26,  23,  12,  56,
        63])

In [72]:
np.delete(a,[0,1,2,3])

array([61, 60, 53, 52, 28, 70, 26, 23, 12, 56, 63])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [73]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [74]:
np.intersect1d(m,n)

array([3, 4, 5])

In [75]:
np.setdiff1d(m,n)

array([1, 2])

In [76]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [81]:
np.in1d(n,4)

array([False,  True, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [82]:
a

array([110, 530,  65,  46,  61,  60,  53,  52,  28,  70,  26,  23,  12,
        56,  63])

In [83]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 65, 46, 61, 60, 53, 52, 28, 70, 26, 25, 25, 56, 63])